export const {
  // C
  CLOUDINARY_IMAGE_CLOUD_NAME,
  CLOUDINARY_IMAGE_API_KEY,
  CLOUDINARY_IMAGE_API_SECRET,
  CLOUDINARY_MAIN_FOLDER,
  CLOUDINARY_PRODUCT_CLOUD_NAME,
  CLOUDINARY_PRODUCT_API_KEY,
  CLOUDINARY_PRODUCT_API_SECRET,
  CLOUDINARY_VIDEO_CLOUD_NAME,
  CLOUDINARY_VIDEO_API_KEY,
  CLOUDINARY_VIDEO_API_SECRET,

  // E
  EMAIL_HOST,
  EMAIL_PORT,
  EMAIL_SECURE,
  EMAIL_USER,
  EMAIL_PASS,
  EMAIL_FROM,

  // F
  FRONTEND_LOCAL_HOST_CLIENT_URL,
  FRONTEND_LOCAL_HOST_ADMIN_URL,
  FRONTEND_LOCAL_HOST_MASTER_URL,
  FRONTEND_LOCAL_HOST_PUBLIC_URL_1,
  FRONTEND_LOCAL_HOST_PUBLIC_URL_2,
  FRONTEND_PRODUCTION_CLIENT_URL,
  FRONTEND_PRODUCTION_ADMIN_URL,
  FRONTEND_PRODUCTION_MASTER_URL,

  // G
  GITHUB_CLIENT_ID,
  GITHUB_CLIENT_SECRET,
  GITHUB_REDIRECT_URI,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  GOOGLE_REDIRECT_URI,

  // J
  JWT_SECRET,

  // L
  LINKEDIN_CLIENT_ID,
  LINKEDIN_CLIENT_SECRET,
  LINKEDIN_REDIRECT_URI,

  // M
  MISTRAL_API_KEY, // Mistral automatically read it with this name only don't change it
  MISTRAL_API_KEY_POST,
  MISTRAL_API_KEY_GET,
  MONGODB_URI,

  // N
  NODE_ENV,

  // P
  PORT,

  // R
  RAZORPAY_KEY_ID,
  RAZORPAY_KEY_SECRET,
  RAZORPAY_WEBHOOK_SECRET,
}: // REDIS_HOST,
// REDIS_PORT,
// REDIS_PASSWORD,
// REDIS_USERNAME,
NodeJS.ProcessEnv = process.env;
