export const razorpayOrder = {
  amount: 12800,
  amount_due: 12800,
  amount_paid: 0,
  attempts: 0,
  created_at: 1765971941,
  currency: "INR",
  entity: "order",
  id: "order_RsfPa8ECVAqhM9",
  notes: {
    buyer_contact: "9730870409",
    buyer_email: "master@gmail.com",
    buyer_id: "68eba546a64e416361e2595d",
    buyer_name: "Master Account",
    db_order_id: "694297e52aa64c09b4a085bb",
  },
  offer_id: null,
  receipt: "order_receipt_1765971941650_1884",
  status: "created",
};

export const paymentCapturedUPI = {
  id: "pay_RsfXH1KzllgZGW",
  entity: "payment",
  amount: 12800,
  currency: "INR",
  status: "captured",
  order_id: "order_RsfPa8ECVAqhM9",
  invoice_id: null,
  international: false,
  method: "upi",
  amount_refunded: 0,
  refund_status: null,
  captured: true,
  description:
    "Ordered by Master Account, with Razorpay secure payment gateway.",
  card_id: null,
  bank: null,
  wallet: null,
  vpa: "test@ybl",
  email: "master@gmail.com",
  contact: "+919730870409",
  notes: {
    db_order_id: "694297e52aa64c09b4a085bb",
    buyer_id: "68eba546a64e416361e2595d",
    buyer_name: "Master Account",
    buyer_email: "master@gmail.com",
    buyer_contact: "9730870409",
  },
  fee: 302,
  tax: 46,
  error_code: null,
  error_description: null,
  error_source: null,
  error_step: null,
  error_reason: null,
  acquirer_data: {
    rrn: "138893338685",
    upi_transaction_id: "CFDB4489A6A732703532955A29C99447",
  },
  created_at: 1765972379,
  reward: null,
  upi: { vpa: "test@ybl", flow: "collect" },
  base_amount: 12800,
};

export const orderPaidUPI = {
  id: "pay_RsfXH1KzllgZGW",
  entity: "payment",
  amount: 12800,
  currency: "INR",
  status: "captured",
  order_id: "order_RsfPa8ECVAqhM9",
  invoice_id: null,
  international: false,
  method: "upi",
  amount_refunded: 0,
  refund_status: null,
  captured: true,
  description:
    "Ordered by Master Account, with Razorpay secure payment gateway.",
  card_id: null,
  bank: null,
  wallet: null,
  vpa: "test@ybl",
  email: "master@gmail.com",
  contact: "+919730870409",
  notes: {
    db_order_id: "694297e52aa64c09b4a085bb",
    buyer_id: "68eba546a64e416361e2595d",
    buyer_name: "Master Account",
    buyer_email: "master@gmail.com",
    buyer_contact: "9730870409",
  },
  fee: 302,
  tax: 46,
  error_code: null,
  error_description: null,
  error_source: null,
  error_step: null,
  error_reason: null,
  acquirer_data: {
    rrn: "138893338685",
    upi_transaction_id: "CFDB4489A6A732703532955A29C99447",
  },
  created_at: 1765972379,
  reward: null,
  upi: { vpa: "test@ybl", flow: "collect" },
};

export const paymentCapturedCARD = {
  id: "pay_RsgJDX1F4l70NL",
  entity: "payment",
  amount: 12800,
  currency: "INR",
  status: "captured",
  order_id: "order_RsgHggD2AxJ6xw",
  invoice_id: null,
  international: false,
  method: "card",
  amount_refunded: 0,
  refund_status: null,
  captured: true,
  description:
    "Ordered by Master Account, with Razorpay secure payment gateway.",
  card_id: "card_RsgJDkB6F9VRef",
  card: {
    id: "card_RsgJDkB6F9VRef",
    entity: "card",
    name: "",
    last4: "0153",
    network: "Visa",
    type: "credit",
    issuer: "UTIB",
    international: false,
    emi: true,
    sub_type: "consumer",
    token_iin: null,
  },
  bank: null,
  wallet: null,
  vpa: null,
  email: "master@gmail.com",
  contact: "+919730870409",
  notes: {
    db_order_id: "6942a3e64d5c715738fbe243",
    buyer_id: "68eba546a64e416361e2595d",
    buyer_name: "Master Account",
    buyer_email: "master@gmail.com",
    buyer_contact: "9730870409",
  },
  fee: 256,
  tax: 0,
  error_code: null,
  error_description: null,
  error_source: null,
  error_step: null,
  error_reason: null,
  acquirer_data: { auth_code: "104881" },
  created_at: 1765975102,
  reward: null,
  base_amount: 12800,
};

export const orderPaidCARD = {
  id: "pay_RsgJDX1F4l70NL",
  entity: "payment",
  amount: 12800,
  currency: "INR",
  status: "captured",
  order_id: "order_RsgHggD2AxJ6xw",
  invoice_id: null,
  international: false,
  method: "card",
  amount_refunded: 0,
  refund_status: null,
  captured: true,
  description:
    "Ordered by Master Account, with Razorpay secure payment gateway.",
  card_id: "card_RsgJDkB6F9VRef",
  card: {
    id: "card_RsgJDkB6F9VRef",
    entity: "card",
    name: "",
    last4: "0153",
    network: "Visa",
    type: "credit",
    issuer: "UTIB",
    international: false,
    emi: true,
    sub_type: "consumer",
    token_iin: null,
  },
  bank: null,
  wallet: null,
  vpa: null,
  email: "master@gmail.com",
  contact: "+919730870409",
  notes: {
    db_order_id: "6942a3e64d5c715738fbe243",
    buyer_id: "68eba546a64e416361e2595d",
    buyer_name: "Master Account",
    buyer_email: "master@gmail.com",
    buyer_contact: "9730870409",
  },
  fee: 256,
  tax: 0,
  error_code: null,
  error_description: null,
  error_source: null,
  error_step: null,
  error_reason: null,
  acquirer_data: { auth_code: "104881" },
  created_at: 1765975102,
  reward: null,
};

export const paymentCapturedNETBANKING = {
  id: "pay_RsheexPFIIsIQI",
  entity: "payment",
  amount: 12800,
  currency: "INR",
  status: "captured",
  order_id: "order_RshdhTZof1oObO",
  invoice_id: null,
  international: false,
  method: "netbanking",
  amount_refunded: 0,
  refund_status: null,
  captured: true,
  description:
    "Ordered by Master Account, with Razorpay secure payment gateway.",
  card_id: null,
  bank: "BARB_R",
  wallet: null,
  vpa: null,
  email: "master@gmail.com",
  contact: "+919730870409",
  notes: {
    db_order_id: "6942b68a3bb3470be0273437",
    buyer_id: "68eba546a64e416361e2595d",
    buyer_name: "Master Account",
    buyer_email: "master@gmail.com",
    buyer_contact: "9730870409",
  },
  fee: 302,
  tax: 46,
  error_code: null,
  error_description: null,
  error_source: null,
  error_step: null,
  error_reason: null,
  acquirer_data: { bank_transaction_id: "4810972" },
  created_at: 1765979841,
  reward: null,
  base_amount: 12800,
};

export const orderPaidNETBANKING = {
  id: "pay_RsheexPFIIsIQI",
  entity: "payment",
  amount: 12800,
  currency: "INR",
  status: "captured",
  order_id: "order_RshdhTZof1oObO",
  invoice_id: null,
  international: false,
  method: "netbanking",
  amount_refunded: 0,
  refund_status: null,
  captured: true,
  description:
    "Ordered by Master Account, with Razorpay secure payment gateway.",
  card_id: null,
  bank: "BARB_R",
  wallet: null,
  vpa: null,
  email: "master@gmail.com",
  contact: "+919730870409",
  notes: {
    db_order_id: "6942b68a3bb3470be0273437",
    buyer_id: "68eba546a64e416361e2595d",
    buyer_name: "Master Account",
    buyer_email: "master@gmail.com",
    buyer_contact: "9730870409",
  },
  fee: 302,
  tax: 46,
  error_code: null,
  error_description: null,
  error_source: null,
  error_step: null,
  error_reason: null,
  acquirer_data: { bank_transaction_id: "4810972" },
  created_at: 1765979841,
  reward: null,
};

export const paymentCapturedWALLET = {
  id: "pay_RshhNf3X78AmL4",
  entity: "payment",
  amount: 12800,
  currency: "INR",
  status: "captured",
  order_id: "order_Rshh7J5ATZlfsK",
  invoice_id: null,
  international: false,
  method: "wallet",
  amount_refunded: 0,
  refund_status: null,
  captured: true,
  description:
    "Ordered by Master Account, with Razorpay secure payment gateway.",
  card_id: null,
  bank: null,
  wallet: "airtelmoney",
  vpa: null,
  email: "master@gmail.com",
  contact: "+919730870409",
  notes: {
    db_order_id: "6942b74c3bb3470be0273480",
    buyer_id: "68eba546a64e416361e2595d",
    buyer_name: "Master Account",
    buyer_email: "master@gmail.com",
    buyer_contact: "9730870409",
  },
  fee: 302,
  tax: 46,
  error_code: null,
  error_description: null,
  error_source: null,
  error_step: null,
  error_reason: null,
  acquirer_data: { transaction_id: null },
  created_at: 1765979996,
  reward: null,
};

export const orderPaidWALLET = {
  id: "pay_RshhNf3X78AmL4",
  entity: "payment",
  amount: 12800,
  currency: "INR",
  status: "captured",
  order_id: "order_Rshh7J5ATZlfsK",
  invoice_id: null,
  international: false,
  method: "wallet",
  amount_refunded: 0,
  refund_status: null,
  captured: true,
  description:
    "Ordered by Master Account, with Razorpay secure payment gateway.",
  card_id: null,
  bank: null,
  wallet: "airtelmoney",
  vpa: null,
  email: "master@gmail.com",
  contact: "+919730870409",
  notes: {
    db_order_id: "6942b74c3bb3470be0273480",
    buyer_id: "68eba546a64e416361e2595d",
    buyer_name: "Master Account",
    buyer_email: "master@gmail.com",
    buyer_contact: "9730870409",
  },
  fee: 302,
  tax: 46,
  error_code: null,
  error_description: null,
  error_source: null,
  error_step: null,
  error_reason: null,
  acquirer_data: { transaction_id: null },
  created_at: 1765979996,
  reward: null,
  base_amount: 12800,
};
