export const {
  // C
  CLOUDINARY_IMAGE_CLOUD_NAME,
  CLOUDINARY_IMAGE_API_KEY,
  CLOUDINARY_IMAGE_API_SECRET,
  CLOUDINARY_MAIN_FOLDER,
  CLOUDINARY_PRODUCT_CLOUD_NAME,
  CLOUDINARY_PRODUCT_API_KEY,
  CLOUDINARY_PRODUCT_API_SECRET,
  CLOUDINARY_VIDEO_CLOUD_NAME,
  CLOUDINARY_VIDEO_API_KEY,
  CLOUDINARY_VIDEO_API_SECRET,

  // F
  FRONTEND_LOCAL_HOST_CLIENT_URL,
  FRONTEND_LOCAL_HOST_ADMIN_URL,
  FRONTEND_LOCAL_HOST_MASTER_URL,
  FRONTEND_LOCAL_HOST_PUBLIC_URL_1,
  FRONTEND_LOCAL_HOST_PUBLIC_URL_2,
  FRONTEND_PRODUCTION_CLIENT_URL,
  FRONTEND_PRODUCTION_ADMIN_URL,
  FRONTEND_PRODUCTION_MASTER_URL,

  // J
  JWT_SECRET,

  // M
  MONGODB_URI,

  // N
  NODE_ENV,

  // P
  PORT,
} = process.env;
